# Generated by Django 5.0.3 on 2024-04-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
