# Generated by Django 5.0.3 on 2024-04-07 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='userId',
            field=models.ForeignKey(default='773bce3d-0419-4f64-9a36-5e726a3a2e68', on_delete=django.db.models.deletion.CASCADE, to='UserProfile.userprofile'),
            preserve_default=False,
        ),
    ]
