# Generated by Django 5.0.3 on 2024-04-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.CharField(default='qwe', max_length=1000),
            preserve_default=False,
        ),
    ]
