# Generated by Django 5.0.3 on 2024-04-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
