# Generated by Django 5.0.3 on 2024-04-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
