# Generated by Django 5.0.3 on 2024-04-17 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_alter_userprofile_name'),
        ('documents', '0005_alter_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('file', models.FileField(upload_to='uploads/')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.userprofile')),
            ],
        ),
    ]
