# Generated by Django 5.0.3 on 2024-04-17 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_alter_userprofile_name'),
        ('documents', '0007_alter_qrcode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.userprofile'),
        ),
    ]
