# Generated by Django 5.0.3 on 2024-04-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_chroniccondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='chroniccondition',
            name='date',
            field=models.DateTimeField(default='2024-04-07T14:50:36Z'),
            preserve_default=False,
        ),
    ]
