# Generated by Django 5.0.3 on 2024-04-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_chroniccondition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
