# Generated by Django 5.0.3 on 2024-04-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointmets_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmets',
            name='doctorName',
            field=models.CharField(max_length=500),
        ),
    ]
